version: '2'

services:
  db:
    build: db
    ports:
      - '5432:5432'
    read_only: true
    restart: always
    volumes:
      - postgres_database:/var/lib/postgresql/data:Z
      - ./volumes/db_dumps/:/db_dumps/
      #- /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost

  mattermost:
    build:
      context: mattermost
    restart: unless-stopped
    volumes:
      - ./volumes/mattermost/config:/mattermost/config:rw
      - ./volumes/mattermost/data:/mattermost/data:rw
      - ./volumes/mattermost/logs:/mattermost/logs:rw
      - ./volumes/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/mattermost/client-plugins:/mattermost/client/plugins:rw
      #- /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json

  nginx:
    build: nginx
    ports:
      - '9090:9090'
      - '443:443'
    read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/nginx/cert:/cert:ro
      #- /etc/localtime:/etc/localtime:ro

  node:
    build: node
    ports:
      - '8080:8080'
    read_only: false
    command: 'npm start'
    volumes:
      - ./node/:/usr/src/app/
      - /usr/src/app/node_modules/

volumes:
    postgres_database:
        external: true
