version: "2.2"

services:
  db:
    container_name: kohdataan-backend_db_1
    build:
      context: db
      network: host
    ports:
      - "5432:5432"
    read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - ./volumes/db_dumps/:/db_dumps/
      #- /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost

  mattermost:
    container_name: kohdataan-backend_mattermost_1
    build:
      context: mattermost
    restart: unless-stopped
    volumes:
      - ./volumes/mattermost/config:/mattermost/config:rw
      - ./volumes/mattermost/data:/mattermost/data:rw
      - ./volumes/mattermost/logs:/mattermost/logs:rw
      - ./volumes/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/mattermost/client-plugins:/mattermost/client/plugins:rw
      #- /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json

  nginx:
    container_name: kohdataan-backend_nginx_1
    build: nginx
    ports:
      - "9090:9090"
    read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/nginx/cert:/cert:ro
      - ./volumes/nginx/conf:/conf:ro
      #- /etc/localtime:/etc/localtime:ro

  node:
    container_name: kohdataan-backend_node_1
    build:
      context: node
      network: host
    ports:
      - "8080:8080"
    read_only: true
    restart: unless-stopped
    volumes:
      - ./node/:/usr/src/app/
      - /usr/src/app/node_modules/
      - ./volumes/node/logs:/var/log/node:rw
