POST http://localhost:9090/api/v4/users/login

{
    "login_id": "janne.timonen@perfektio.fi",
    "password": "passwordtesti"
}


###

OPTIONS http://localhost:9090/api/users/login/
Origin: http://www.example.com
Access-Control-Request-Method: GET
Access-Control-Request-Headers: X-Requested-With

###

POST http://localhost:9090/node_api/user/
Content-Type: application/json

{
    "username": "woland",
    "email": "janne.timonen@perfektio.com",
    "password": "passwordtesti",
    "nickname": null,
    "description": null,
    "profileReady": false,
    "tutorialWatched": "false"
}

###
GET http://localhost:9090/node_api/user/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJ3b2xhbmQiLCJlbWFpbCI6Imphbm5lLnRpbW9uZW5AcGVyZmVrdGlvLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEyJHZnTDF6TnBiN2FKZUNuZlNBNHZxcXVMOS5BWkRzc2d1M2l2U0QyVlNKd3FLSnJzLnlzdS55Iiwibmlja25hbWUiOm51bGwsImRlc2NyaXB0aW9uIjpudWxsLCJwcm9maWxlUmVhZHkiOmZhbHNlLCJjcmVhdGVkQXQiOiIyMDE5LTA1LTA4VDExOjAzOjUwLjI1OFoiLCJ1cGRhdGVkQXQiOiIyMDE5LTA1LTA4VDExOjAzOjUwLjI1OFoiLCJpYXQiOjE1NTczMTM3OTl9.eoCrySNvmgsB32hd1A1Ju_pVS5Ic6QLFJ9ZTeo9nLeU
###
DELETE http://localhost:9090/node_api/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDAsInVzZXJuYW1lIjoid29sYW5kIiwiZW1haWwiOiJqYW5uZS50aW1vbmVuQHBlcmZla3Rpby5jb20iLCJwYXNzd29yZCI6IiQyYiQxMiRrUkNLZXhIR203aC9xbWR2Ynp4cnZ1bUtwWG93R3lKVWF6SDZEc1NUU0xRWG5nSlBtaS9JLiIsImNyZWF0ZWRBdCI6IjIwMTktMDUtMDdUMTY6MDQ6NTEuMTYxWiIsInVwZGF0ZWRBdCI6IjIwMTktMDUtMDdUMTY6MDQ6NTEuMTYxWiIsImlhdCI6MTU1NzI0NzQyOH0.C_jdx9u6yVldlYddvyL9qsDWIOXm1iNTPxAjgmDywuE
###
POST http://localhost:9090/node_api/auth/login
Content-Type: application/json

{
    "email": "janne.timonen@perfektio.com",
    "password": "passwordtesti"
}

###
PATCH http://localhost:9090/node_api/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJ3b2xhbmQiLCJlbWFpbCI6Imphbm5lLnRpbW9uZW5AcGVyZmVrdGlvLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEyJHZnTDF6TnBiN2FKZUNuZlNBNHZxcXVMOS5BWkRzc2d1M2l2U0QyVlNKd3FLSnJzLnlzdS55Iiwibmlja25hbWUiOm51bGwsImRlc2NyaXB0aW9uIjpudWxsLCJwcm9maWxlUmVhZHkiOmZhbHNlLCJjcmVhdGVkQXQiOiIyMDE5LTA1LTA4VDExOjAzOjUwLjI1OFoiLCJ1cGRhdGVkQXQiOiIyMDE5LTA1LTA4VDExOjAzOjUwLjI1OFoiLCJpYXQiOjE1NTczMTM3OTl9.eoCrySNvmgsB32hd1A1Ju_pVS5Ic6QLFJ9ZTeo9nLeU
Content-Type: application/json

{
    "username": "woland",
    "email": "janne.timonen@perfektio.com",
    "nickname": "woland",
    "description": "Testikuvaus",
    "profileReady": "false",
    "tutorialWatched": "false"
}

###
GET http://localhost:9090/node_api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJ3b2xhbmQiLCJlbWFpbCI6Imphbm5lLnRpbW9uZW5AcGVyZmVrdGlvLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEyJDVRWXpDUFdienBudS5aRWZ0UG5HNi5OeXp6R1ViS05scGthUUVDc01zOWJSQmJxVktlekhtIiwiY3JlYXRlZEF0IjoiMjAxOS0wNS0wN1QxMzo0ODo1NC4yMDZaIiwidXBkYXRlZEF0IjoiMjAxOS0wNS0wN1QxMzo0ODo1NC4yMDZaIiwiaWF0IjoxNTU3MjM2OTYzfQ.vt7VFmPN0x9fiCs-uoSYMBz3TA9qBLJS_yPLtS8JhY0